'\" t
.\"     Title: despack
.\"    Author: despack team
.\"      Date: 20\ \&July\ \&2020
.\"    Manual: DESPACK
.\"    Source: DESPACK 20.07.20
.\"  Language: English
.\"
.TH "DESPACK" "8" "20\ \&July\ \&2020" "DESPACK 20.07.20" "DESPACK"

.SH "NAME"
despack \- command\-line interface
.SH "SYNOPSIS"
.HP \w'\fBdespack\fR\ 'u
\fBdespack [\fB\-h\fR] [\fB\]
